In [69]:
import numpy as np
import pandas as pd

In [70]:
raw_data= pd.read_csv('1000.txt',sep="delimeter", header=None, engine='python')

In [71]:
raw_data.head()

                                                   0
0                   http://www.liquidgeneration.com/
1                        http://www.onlineanime.org/
2  http://www.ceres.dti.ne.jp/~nekoi/senno/senfir...
3                         http://www.galeon.com/kmh/
4                        http://www.fanworkrecs.com/

In [72]:
raw_data.columns=["websites"] 
raw_data.head()

                                            websites
0                   http://www.liquidgeneration.com/
1                        http://www.onlineanime.org/
2  http://www.ceres.dti.ne.jp/~nekoi/senno/senfir...
3                         http://www.galeon.com/kmh/
4                        http://www.fanworkrecs.com/

In [73]:
seperation_of_protocol = raw_data['websites'].str.split("://",expand = True)

In [74]:
seperation_of_protocol.head()

      0                                               1     2
0  http                       www.liquidgeneration.com/  None
1  http                            www.onlineanime.org/  None
2  http  www.ceres.dti.ne.jp/~nekoi/senno/senfirst.html  None
3  http                             www.galeon.com/kmh/  None
4  http                            www.fanworkrecs.com/  None

In [75]:
type(seperation_of_protocol)

pandas.core.frame.DataFrame

In [76]:
seperation_of_protocol.columns=["Protocol","domain_name","address"] 
seperation_of_protocol.head()

  Protocol                                     domain_name address
0     http                       www.liquidgeneration.com/    None
1     http                            www.onlineanime.org/    None
2     http  www.ceres.dti.ne.jp/~nekoi/senno/senfirst.html    None
3     http                             www.galeon.com/kmh/    None
4     http                            www.fanworkrecs.com/    None

In [77]:
seperation_domain_name = seperation_of_protocol['domain_name'].str.split("/",1,expand = True)

In [78]:
seperation_domain_name.columns=["Domain_name","Address"]
seperation_domain_name.head()

                Domain_name                     Address
0  www.liquidgeneration.com
1       www.onlineanime.org
2       www.ceres.dti.ne.jp  ~nekoi/senno/senfirst.html
3            www.galeon.com                        kmh/
4       www.fanworkrecs.com

In [79]:
splitted_data = pd.concat([seperation_of_protocol['Protocol'],seperation_domain_name],axis=1)

In [80]:
splitted_data.columns = ['protocol','domain_name','address']

In [81]:
splitted_data.head()

  protocol               domain_name                     address
0     http  www.liquidgeneration.com
1     http       www.onlineanime.org
2     http       www.ceres.dti.ne.jp  ~nekoi/senno/senfirst.html
3     http            www.galeon.com                        kmh/
4     http       www.fanworkrecs.com

In [82]:
type(splitted_data)

pandas.core.frame.DataFrame

In [83]:
splitted_data.isnull().sum()

protocol         0
domain_name      0
address        143
dtype: int64

In [84]:
splitted_data = splitted_data.dropna()

In [85]:
splitted_data.isnull().sum()

protocol       0
domain_name    0
address        0
dtype: int64

### Features Extraction

In [86]:
def long_url(l):
    """This function is defined in order to differntiate website based on the length of the URL"""
    if len(l) < 54:
        return 0
    elif len(l) >= 54 and len(l) <= 75:
        return 2
    return 1

In [87]:
splitted_data['long_url'] = splitted_data['address'].apply(long_url)

In [88]:
splitted_data[splitted_data.long_url == 0].head()

  protocol               domain_name                     address  long_url
0     http  www.liquidgeneration.com                                     0
1     http       www.onlineanime.org                                     0
2     http       www.ceres.dti.ne.jp  ~nekoi/senno/senfirst.html         0
3     http            www.galeon.com                        kmh/         0
4     http       www.fanworkrecs.com                                     0

In [89]:
def have_at_symbol(l):
    """This function is used to check whether the URL contains @ symbol or not"""
    if "@" in l:
        return 1
    return 0

In [90]:
splitted_data['having_@_symbol'] = splitted_data['address'].apply(have_at_symbol)

In [91]:
splitted_data.head()

,protocol,domain_name,address,long_url,having_@_symbol
0,http,www.liquidgeneration.com,,0,0
1,http,www.onlineanime.org,,0,0
2,http,www.ceres.dti.ne.jp,~nekoi/senno/senfirst.html,0,0
3,http,www.galeon.com,kmh/,0,0
4,http,www.fanworkrecs.com,,0,0

In [92]:
def redirection(l):
    """If the url has symbol(//) after protocol then such URL is to be classified as phishing """
    if "//" in l:
        return 1
    return 0

In [93]:
splitted_data['redirection_//_symbol'] = splitted_data['domain_name'].apply(redirection)

In [94]:
splitted_data.head()

,protocol,domain_name,address,long_url,having_@_symbol,redirection_//_symbol
0,http,www.liquidgeneration.com,,0,0,0
1,http,www.onlineanime.org,,0,0,0
2,http,www.ceres.dti.ne.jp,~nekoi/senno/senfirst.html,0,0,0
3,http,www.galeon.com,kmh/,0,0,0
4,http,www.fanworkrecs.com,,0,0,0

In [95]:
def prefix_suffix_seperation(l):
    if '-' in l:
        return 1
    return 0

In [96]:
splitted_data['prefix_suffix_seperation'] = splitted_data['domain_name'].apply(prefix_suffix_seperation)

In [97]:
splitted_data.head()

,protocol,domain_name,address,long_url,having_@_symbol,redirection_//_symbol,prefix_suffix_seperation
0,http,www.liquidgeneration.com,,0,0,0,0
1,http,www.onlineanime.org,,0,0,0,0
2,http,www.ceres.dti.ne.jp,~nekoi/senno/senfirst.html,0,0,0,0
3,http,www.galeon.com,kmh/,0,0,0,0
4,http,www.fanworkrecs.com,,0,0,0,0

In [98]:
def sub_domains(l):
    if l.count('.') < 3:
        return 0
    elif l.count('.') == 3:
        return 2
    return 1

In [99]:
splitted_data['sub_domains'] = splitted_data['domain_name'].apply(sub_domains)

In [100]:
splitted_data.head()

,protocol,domain_name,address,long_url,having_@_symbol,redirection_//_symbol,prefix_suffix_seperation,sub_domains
0,http,www.liquidgeneration.com,,0,0,0,0,0
1,http,www.onlineanime.org,,0,0,0,0,0
2,http,www.ceres.dti.ne.jp,~nekoi/senno/senfirst.html,0,0,0,0,1
3,http,www.galeon.com,kmh/,0,0,0,0,0
4,http,www.fanworkrecs.com,,0,0,0,0,0

In [101]:
import re
def having_ip_address(url):
    match=re.search('(([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\/)|'  #IPv4
                    '((0x[0-9a-fA-F]{1,2})\\.(0x[0-9a-fA-F]{1,2})\\.(0x[0-9a-fA-F]{1,2})\\.(0x[0-9a-fA-F]{1,2})\\/)'  #IPv4 in hexadecimal
                    '(?:[a-fA-F0-9]{1,4}:){7}[a-fA-F0-9]{1,4}',url)     #Ipv6
    if match:
        #print match.group()
        return 1
    else:
        #print 'No matching pattern found'
        return 0

In [102]:
splitted_data['having_ip_address'] = raw_data['websites'].apply(having_ip_address)

In [103]:
splitted_data.head()

,protocol,domain_name,address,long_url,having_@_symbol,redirection_//_symbol,prefix_suffix_seperation,sub_domains,having_ip_address
0,http,www.liquidgeneration.com,,0,0,0,0,0,0
1,http,www.onlineanime.org,,0,0,0,0,0,0
2,http,www.ceres.dti.ne.jp,~nekoi/senno/senfirst.html,0,0,0,0,1,0
3,http,www.galeon.com,kmh/,0,0,0,0,0,0
4,http,www.fanworkrecs.com,,0,0,0,0,0,0

In [104]:
#we have imported re module in the above feature. So need not to import again
def shortening_service(url):
    match=re.search('bit\.ly|goo\.gl|shorte\.st|go2l\.ink|x\.co|ow\.ly|t\.co|tinyurl|tr\.im|is\.gd|cli\.gs|'
                    'yfrog\.com|migre\.me|ff\.im|tiny\.cc|url4\.eu|twit\.ac|su\.pr|twurl\.nl|snipurl\.com|'
                    'short\.to|BudURL\.com|ping\.fm|post\.ly|Just\.as|bkite\.com|snipr\.com|fic\.kr|loopt\.us|'
                    'doiop\.com|short\.ie|kl\.am|wp\.me|rubyurl\.com|om\.ly|to\.ly|bit\.do|t\.co|lnkd\.in|'
                    'db\.tt|qr\.ae|adf\.ly|goo\.gl|bitly\.com|cur\.lv|tinyurl\.com|ow\.ly|bit\.ly|ity\.im|'
                    'q\.gs|is\.gd|po\.st|bc\.vc|twitthis\.com|u\.to|j\.mp|buzurl\.com|cutt\.us|u\.bb|yourls\.org|'
                    'x\.co|prettylinkpro\.com|scrnch\.me|filoops\.info|vzturl\.com|qr\.net|1url\.com|tweez\.me|v\.gd|tr\.im|link\.zip\.net',url)
    if match:
        return 1
    else:
        return 0

In [105]:
splitted_data['shortening_service'] = raw_data['websites'].apply(shortening_service)

In [106]:
splitted_data.head()

,protocol,domain_name,address,long_url,having_@_symbol,redirection_//_symbol,prefix_suffix_seperation,sub_domains,having_ip_address,shortening_service
0,http,www.liquidgeneration.com,,0,0,0,0,0,0,0
1,http,www.onlineanime.org,,0,0,0,0,0,0,0
2,http,www.ceres.dti.ne.jp,~nekoi/senno/senfirst.html,0,0,0,0,1,0,0
3,http,www.galeon.com,kmh/,0,0,0,0,0,0,0
4,http,www.fanworkrecs.com,,0,0,0,0,0,0,0

In [107]:
def https_token(url):
    #print(url)
    match=re.search('https|http',url)
    #if match.start(0)==0:
        #url=url[match.end(0):]
    match=re.search('http|https',url)
    if match:
        return 1
    else:
        return 0

In [108]:
splitted_data['https_token'] = splitted_data['protocol'].apply(https_token)

In [109]:
splitted_data.head()

,protocol,domain_name,address,long_url,having_@_symbol,redirection_//_symbol,prefix_suffix_seperation,sub_domains,having_ip_address,shortening_service,https_token
0,http,www.liquidgeneration.com,,0,0,0,0,0,0,0,1
1,http,www.onlineanime.org,,0,0,0,0,0,0,0,1
2,http,www.ceres.dti.ne.jp,~nekoi/senno/senfirst.html,0,0,0,0,1,0,0,1
3,http,www.galeon.com,kmh/,0,0,0,0,0,0,0,1
4,http,www.fanworkrecs.com,,0,0,0,0,0,0,0,1

In [110]:
def abnormal_url_sub(domain,url):
    hostname=domain.name
    match=re.search(hostname,url)
    if match:
        return 0
    else:
        return 1

In [111]:
def abnormal_url_main(domain):
    dns = 0
    try:
        domain_name = whois.whois(domain)
    except:
        dns = 1
        
    if dns == 1:
        return 1
    else:
        return abnormal_url_sub(domain_name)

In [112]:
splitted_data['abnormal_url'] = splitted_data['domain_name'].apply(abnormal_url_main)
splitted_data.head()

,protocol,domain_name,address,long_url,having_@_symbol,redirection_//_symbol,prefix_suffix_seperation,sub_domains,having_ip_address,shortening_service,https_token,abnormal_url
0,http,www.liquidgeneration.com,,0,0,0,0,0,0,0,1,1
1,http,www.onlineanime.org,,0,0,0,0,0,0,0,1,1
2,http,www.ceres.dti.ne.jp,~nekoi/senno/senfirst.html,0,0,0,0,1,0,0,1,1
3,http,www.galeon.com,kmh/,0,0,0,0,0,0,0,1,1
4,http,www.fanworkrecs.com,,0,0,0,0,0,0,0,1,1

In [113]:
from bs4 import BeautifulSoup
import urllib.request
def web_traffic(url):
    try:
        rank = BeautifulSoup(urllib.request.urlopen("http://data.alexa.com/data?cli=10&dat=s&url=" + url).read(), "xml").find("REACH")['RANK']
    except TypeError:
        return 1
    rank= int(rank)
    if (rank<100000):
        return 0
    else:
        return 2

In [ ]:
splitted_data['web_traffic'] = raw_data['websites'].apply(web_traffic)

In [ ]:
splitted_data.head()

In [ ]:
import whois
from datetime import datetime
import time
def domain_registration_length_sub(domain):
    expiration_date = domain.expiration_date
    today = time.strftime('%Y-%m-%d')
    today = datetime.strptime(today, '%Y-%m-%d')
    if expiration_date is None:
        return 1
    elif type(expiration_date) is list or type(today) is list :
        return 2             #If it is a type of list then we can't select a single value from list. So,it is regarded as suspected website  
    else:
        registration_length = abs((expiration_date - today).days)
        if registration_length / 365 <= 1:
            return 1
        else:
            return 0

In [ ]:
def domain_registration_length_main(domain):
    dns = 0
    try:
        domain_name = whois.whois(domain)
    except:
        dns = 1
        
    if dns == 1:
        return 1
    else:
        return domain_registration_length_sub(domain_name)

In [ ]:
splitted_data['domain_registration_length'] = splitted_data['domain_name'].apply(domain_registration_length_main)

In [ ]:
splitted_data.head()

In [ ]:
#Testing the above function
domain_registration_length_main('www.google.com')

In [ ]:
domain_registration_length_main('www.w3schools.com')

In [ ]:
def age_of_domain_sub(domain):
    creation_date = domain.creation_date
    expiration_date = domain.expiration_date
    if ((expiration_date is None) or (creation_date is None)):
        return 1
    elif ((type(expiration_date) is list) or (type(creation_date) is list)):
        return 2
    else:
        ageofdomain = abs((expiration_date - creation_date).days)
        if ((ageofdomain/30) < 6):
            return 1
        else:
            return 0

In [ ]:
def age_of_domain_main(domain):
    dns = 0
    try:
        domain_name = whois.whois(domain)
    except:
        dns = 1
        
    if dns == 1:
        return 1
    else:
        return age_of_domain_sub(domain_name)

In [ ]:
splitted_data['age_of_domain'] = splitted_data['domain_name'].apply(age_of_domain_main)

In [ ]:
splitted_data

In [ ]:
def dns_record(domain):
    dns = 0
    try:
        domain_name = whois.whois(domain)
        print(domain_name)
    except:
        dns = 1
        
    if dns == 1:
        return 1
    else:
        return dns

In [ ]:
splitted_data['dns_record'] = splitted_data['domain_name'].apply(dns_record)

In [ ]:
splitted_data

In [ ]:
import socket
def statistical_report(url):
    hostname = url
    h = [(x.start(0), x.end(0)) for x in re.finditer('https://|http://|www.|https://www.|http://www.', hostname)]
    z = int(len(h))
    if z != 0:
        y = h[0][1]
        hostname = hostname[y:]
        h = [(x.start(0), x.end(0)) for x in re.finditer('/', hostname)]
        z = int(len(h))
        if z != 0:
            hostname = hostname[:h[0][0]]
    url_match=re.search('at\.ua|usa\.cc|baltazarpresentes\.com\.br|pe\.hu|esy\.es|hol\.es|sweddy\.com|myjino\.ru|96\.lt|ow\.ly',url)
    try:
        ip_address = socket.gethostbyname(hostname)
        ip_match=re.search('146\.112\.61\.108|213\.174\.157\.151|121\.50\.168\.88|192\.185\.217\.116|78\.46\.211\.158|181\.174\.165\.13|46\.242\.145\.103|121\.50\.168\.40|83\.125\.22\.219|46\.242\.145\.98|107\.151\.148\.44|107\.151\.148\.107|64\.70\.19\.203|199\.184\.144\.27|107\.151\.148\.108|107\.151\.148\.109|119\.28\.52\.61|54\.83\.43\.69|52\.69\.166\.231|216\.58\.192\.225|118\.184\.25\.86|67\.208\.74\.71|23\.253\.126\.58|104\.239\.157\.210|175\.126\.123\.219|141\.8\.224\.221|10\.10\.10\.10|43\.229\.108\.32|103\.232\.215\.140|69\.172\.201\.153|216\.218\.185\.162|54\.225\.104\.146|103\.243\.24\.98|199\.59\.243\.120|31\.170\.160\.61|213\.19\.128\.77|62\.113\.226\.131|208\.100\.26\.234|195\.16\.127\.102|195\.16\.127\.157|34\.196\.13\.28|103\.224\.212\.222|172\.217\.4\.225|54\.72\.9\.51|192\.64\.147\.141|198\.200\.56\.183|23\.253\.164\.103|52\.48\.191\.26|52\.214\.197\.72|87\.98\.255\.18|209\.99\.17\.27|216\.38\.62\.18|104\.130\.124\.96|47\.89\.58\.141|78\.46\.211\.158|54\.86\.225\.156|54\.82\.156\.19|37\.157\.192\.102|204\.11\.56\.48|110\.34\.231\.42',ip_address)  
    except:
        return 1

    if url_match:
        return 1
    else:
        return 0

In [ ]:
splitted_data['statistical_report'] = raw_data['websites'].apply(statistical_report)

In [ ]:
splitted_data.head(30)